### ISSUE TITLE
Cargo audit finds security vuln

### ISSUE THREAD

**Issue by barathrm** [etesync/libetebase#13]
Full log attached. Currently, a `cargo update` is not enough as a work-around since etebase-rs also needs an update.

[log.txt](https://github.com/etesync/libetebase/files/11183703/log.txt)

See also https://github.com/etesync/etebase-rs/pull/42

**Comment by tasn** [comment]
Thanks for the report. I see you had a PR?

**Comment by barathrm** [comment]
Not for libetebase yet. I was thinking it would make sense to fix the dependencies of etebase-rs first, then run cargo update for libetebase? Not really a cargo pro.

**Comment by tasn** [comment]
Yeah, 100%. OK. Let me know how I can help.

**Comment by Skycoder42** [comment]
So, whats the status on this?

**Comment by barathrm** [comment]
> So, whats the status on this?

Waiting for @tasn to tag a new version of https://github.com/etesync/etebase-rs which contains the fixes of https://github.com/etesync/etebase-rs/pull/42 so this (libetebase) can bump its version of etebase-rs

Guess I should've nagged a bit more :D Thanks for reminding us

**Comment by tasn** [comment]
Whoops, I thought we already did! Thanks for the bump. :)

**Comment by tasn** [comment]
Done.
