### ISSUE TITLE
etebase_error_get_message() crash application

### ISSUE THREAD

**Issue by knacky34** [etesync/libetebase#2]
call of `etebase_error_get_message()` seems to crash the application.

### step to reproduce
```cpp
#include <iostream>
#include <etebase/etebase.h>

int main() {
	EtebaseClient *client = etebase_client_new("a", "https://example.com");
	std::cout << "error: " << etebase_error_get_message() << std::endl;
	std::cout << "test" << std::endl;

	return 0;
}
```

* run the above code
* you should see `error: ` but not the `test`

**Comment by tasn** [comment]
If I had to guess, it's because it didn't error so the return is `NULL`. You should only call this function if `client` is `NULL` (so the previous call failed).

**Comment by knacky34** [comment]
You're right the function return nullptr if there is no error
Thank you

**Comment by tasn** [comment]
Glad it's solved!
